### PR TITLE
add body for post request

### PR DESCRIPTION
**Pull request by mgolisch**

### CODE REVIEW

**Comment by krocheck** [comment]
Hi.  What sort of testing have you completed for this PR?

**Comment by josephdadams** [comment]
This would be a nice feature to have included in the master branch. @mgolisch can you follow back up with your testing results?

**Comment by henne-** [comment]
I was about to implement the same feature and pull request it, since it has already been done, I don't have to. 
Why hasn't this been accepted for the master branch? Seems to be working fine, request works when there is a valid object in the textinput and it returns an error if not..

**Comment by josephdadams** [comment]
@willosof can we merge this?

**Comment by haakonnessjoen** [comment]
This is waiting for someone to test it, as @krocheck requested.

**Comment by josephdadams** [comment]
@mgolisch seems to have abandoned it. @henne- has tested it.

**Comment by haakonnessjoen** [comment]
Also updated in master on bitfocus/companion@f67a277 in master branch

**Comment by josephdadams** [comment]
Thank you!!

**Pull request merged**
